name: Build tvOS Rootless

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build App
        run: |
          xcodebuild \
            -project _Project/Browser.xcodeproj \
            -scheme Browser \
            -sdk appletvos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO

      - name: Prepare layout
        run: |
          mkdir -p layout/var/jb/Applications

          APP=$(find ~/Library/Developer/Xcode/DerivedData -name "Browser.app" | head -n 1)

          cp -R "$APP" layout/var/jb/Applications/

      - name: Build DEB
        run: |
          make package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tvOSBrowser-rootless
          path: packages/*.deb
