name: Build IPA (tvOS)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build archive
        run: |
          xcodebuild \
          -project _Project/Browser.xcodeproj \
          -scheme Browser \
          -destination 'generic/platform=tvOS' \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          archive \
          -archivePath build/App.xcarchive

      - name: Export IPA
        run: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
          -archivePath build/App.xcarchive \
          -exportPath build \
          -exportOptionsPlist ExportOptions.plist \
          CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: build/*.ipa
